### ISSUE TITLE
Zipper uses a deprecated means of generating sexps

### ISSUE THREAD

**Issue by stevejb71** [exercism/xocaml#44]
The code for Tree.ml uses ```with sexp``` to generate sexp converters. This is deprecated since 4.03.0, ```[@@deriving sexp]``` is the recommended replacement.

**Comment by bcc32** [comment]
Uh, FWIW, `with sexp` has been deprecated for a while, but I don't believe that has anything to do with the new compiler version.  The relevant syntax extension is [janestreet/ppx_sexp_conv](https://github.com/janestreet/ppx_sexp_conv).

**Comment by kytrinyx** [comment]
@tmcgilchrist do you have any opinions on this one?

**Comment by dvberkel** [comment]
@stevejb71 is correct that `with sexp` is deprecated and that the alternative is a the use of a deriving plugin `[@@deriving sexp]`, as detailed in [janestreet/ppx_sexp_conv](https://github.com/janestreet/ppx_sexp_conv) as pointed out by @bcc32.

The two books that are prominently promoted on the [OCaml website](https://ocaml.org/)

* [_OCaml from the very beginning_](http://ocaml-book.com/) does not even mention s-expressions.
* [_Real World OCaml_](https://realworldocaml.org/) mentions s-expressions but uses the deprecated `with sexp` form.

A quick [search](https://www.google.nl/search?q=ocaml+with+sexp&ie=utf-8&oe=utf-8) also does not mention the deprecation unless you know where to look.

So I am under the following impressions:

1. Beginning users will be more familiar with the `with sexp` expression than the `[@@deriving sexp]` extension.
2. `with sexp` can still be used. It is deprecated because there is a cleaner way to extend the OCaml syntax. I.e. with deriving plugins.
3. Expert users would blink twice when seeing `with sexp` instead of `[@@deriving sexp]`.

So I propose to leave the `with sexp` as is and provide a `HINTS.md` file where we detail the deprecation of the expression and explain the alternative with appropriate pointers.
