### ISSUE TITLE
Unable to run bob exercise: Missing option in Makefile

### ISSUE THREAD

**Issue by kevgathuku** [exercism/xocaml#54]
Hey everyone,
Thanks for coming up with these exercises. They are a great way to learn new languages.

I am experiencing a problem while trying to run the bob exercise.
This is the error I am seeing when trying to use the `Str` module in my solution:
```
+ ocamlfind ocamlopt -linkpkg -g -thread -package oUnit -package core bob.cmx test.cmx -o test.native
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Str referenced from bob.cmx
Command exited with code 2.
```

In order for the make directive to run, I eventually found out that I have to modify the `test.native` directive of the Makefile to be:
```
test.native: *.ml *.mli
	@corebuild -r -quiet -pkg oUnit -pkg str test.native
```
I'm not sure if this is the correct solution, but it has worked for me. 
Is there a way to give the users some direction on how to solve this in case it comes up or was I missing something all along?
Thanks in advance.

**Comment by dvberkel** [comment]
Hi @kevgathuku thanks for taking the time to report a problem you are experiencing. Exercism.io is meant to help people learn a new language. When anyone experiences problems the could be thrown of track, which would be unfortunate.

It is great to hear that you were able to solve your problem. If nothing else, your report could help others that are experiencing similar problems. The way you solved your problem is correct. In effect you have to tell OCaml build tool that you are using a module in your solution.

I totally agree that we could give users a helpful tip when they experience these kind of problems. Maybe you could suggest a hint that would have helped you?

In the meantime I will think of a good place for the actual hint.

**Comment by dvberkel** [comment]
I would suggest to give a hint how on how to solve these kinds of problems on the [_running the tests_](http://exercism.io/languages/ocaml/tests) part of the OCaml track. @kevgathuku what do you think?

**Comment by kevgathuku** [comment]
Hi @dvberkel thanks for your reply. It was frustrating to experience an error like this one and not have a place I could refer to. There wasn't a lot of useful information I could find online. 

Including a tip would be extremely useful to other users in future, especially for this error.

I'm thinking it should be an extra section on it's own, with a sort of QA style of errors, their causes and common solutions. e.g. the format in this [WIki page](http://www.willforge.fr/wikisys/index.php?title=OCaml/Error_messages)
I would really love to hear your feedback on that suggestion.
If you're okay with it, I can get started on it.

**Comment by dvberkel** [comment]
@kevgathuku I can relate to the frustration of a bug that when you just start out learning a language. I think you are right that a tip would help future users.

I think that a Wiki page would be beneficial, but I would like to ask @kytrinyx, because I am not sure what the exercism.io way would be.

None the less, starting with a draft of a tip can't hurt. Where it eventually end up is an other question.

**Comment by kevgathuku** [comment]
Thanks @dvberkel. I'll start on it soon, as we wait for a response regarding where to put it.

For the [Wiki link](http://www.willforge.fr/wikisys/index.php?title=OCaml/Error_messages) I included, this was to act a reference to how I think the content should be structured.

**Comment by kytrinyx** [comment]
> In the meantime I will think of a good place for the actual hint.

The best place for the hint would be a `HINTS.md` file in the exercise directory. This will be included in the README that gets delivered along with the test suite when people fetch the exercise.

```
exercises/bob/
├── Makefile
├── bob.mli
├── example.ml
├── HINTS.md
└── test.ml
```

**Comment by dvberkel** [comment]
@kytrinyx where would hints be placed when they are not exercise specific?

**Comment by kytrinyx** [comment]
For hints that are general to the track, the `SETUP.md` file in the root of the repository will do what you need: https://github.com/exercism/xocaml/blob/master/SETUP.md

**Comment by dvberkel** [comment]
Hi @kevgathuku 

How are you? Are you still interested in contributing your tips? Do you need any assistance?

**Comment by kevgathuku** [comment]
Hi @dvberkel I'm still interested in contributing. I'll send my first draft soon and hopefully I can get some suggestions on making it better.

**Comment by dvberkel** [comment]
@kevgathuku Great! Looking forward to your contribution

**Comment by dvberkel** [comment]
I am closing this issue because @kevgathuku pull request #56 provides a useful hint that would solve the problem
